name: AI Security Pipeline

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    env:
      REPORTS_DIR: reports
      HOST: testphp.vulnweb.com
      ENTERPRISE_DEBUG: "true"
      TARGET_URL: "http://testphp.vulnweb.com/"
      OLLAMA_MODEL: mistral
      
    steps:
    # -------------------------------------------------
    # Checkout Repo (MANDATORY)
    # -------------------------------------------------
    - name: Checkout Repository
      uses: actions/checkout@v4

    # -------------------------------------------------
    # Setup Python
    # -------------------------------------------------
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: pip install -r requirements.txt

    # -------------------------------------------------
    # Create Reports Folder
    # -------------------------------------------------
    - name: Create Reports Directory
      run: mkdir -p reports

    # -------------------------------------------------
    # Debug Workspace (VERY IMPORTANT)
    # -------------------------------------------------
    - name: Debug Files
      run: |
        pwd
        ls -la
        
    # -------------------------------------------------
    # Install Ollama + Run Ollma + Test Ollma AI 
    # -------------------------------------------------
    - name: Install Ollama + Run Ollma + Test Ollma AI 
      run: python orchestrator.py

    # -------------------------------------------------
    # Start ZAP
    # -------------------------------------------------
    - name: Start ZAP proxy tool
      run: |
        docker run -d -p 8080:8080 ghcr.io/zaproxy/zaproxy:stable \
          zap.sh -daemon -port 8080 -host 0.0.0.0
        sleep 30
        
    # -------------------------------------------------
    # Run Orchestrator
    # -------------------------------------------------
    - name: Run Security Pipeline
      run: python orchestrator.py

    # -------------------------------------------------
    # Upload Artifacts
    # -------------------------------------------------
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: reports/
