name: AI Security Pipeline

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    env:
      REPORTS_DIR: reports
      HOST: testphp.vulnweb.com
      ENTERPRISE_DEBUG: "true"
      TARGET_URL: "http://testphp.vulnweb.com/"
      OLLAMA_MODEL: mistral
      
    steps:
    # -------------------------------------------------
    # Checkout Repo (MANDATORY)
    # -------------------------------------------------
    - name: Checkout Repository
      uses: actions/checkout@v4

    # -------------------------------------------------
    # Setup Python
    # -------------------------------------------------
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: pip install -r requirements.txt

    # -------------------------------------------------
    # Create Reports Folder
    # -------------------------------------------------
    - name: Create Reports Directory
      run: mkdir -p reports

    # -------------------------------------------------
    # Debug Workspace (VERY IMPORTANT)
    # -------------------------------------------------
    - name: Debug Files
      run: |
        pwd
        ls -laR
        
    # -------------------------------------------------
    # Install Ollama + Run Ollma + Test Ollma AI 
    # -------------------------------------------------
    - name: Install Ollama + Run Ollma + Test Ollma AI 
      run: python ollama_test_agent.py

    # Install and Run Semgrep
    # -------------------------------------------------
    - name: Install and Run Semgrep
      run: python agents/semgrep_agent.py

    # Install and Run  Trufflehog agent
    # -------------------------------------------------
    - name: Install and Run  agent
      run: python  agents/trufflehog_agent.py

   # Install and Run Nmap
    # -------------------------------------------------
    - name: Install and Run 
      run: python  agents/nmap_agent.py
    
    # Install and Run zap_agent 
    # -------------------------------------------------
    - name: Install and Run zap_agent
      run: python agents/zap_agent.py
        
    # -------------------------------------------------
    # Run Orchestrator
    # -------------------------------------------------
    - name: Run Security Pipeline
      run: python orchestrator.py

    # -------------------------------------------------
    # Upload Artifacts
    # -------------------------------------------------
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: reports/
