name: Run Ollama and ZAP Agent

on:
  workflow_dispatch:

jobs:
  ZAP_Scan_AI_Via_Ollama:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Create and activate virtual environment, install deps, run scripts
      - name: Install Ollama, ZAP and run agent scripts
        run: |
          ls -alr
          # Setup Python Environment
          python3 -m venv zapenv
          source zapenv/bin/activate
          pip install --upgrade pip
          #
          # Run your prerequisite script
          python3 agents/pre_req.py
          #
          # Run your enterprise agent script
          python3 agents/ollama_and_ZAP_Run.py
          sleep 30
          python3 agents/zap_agent_v4.py
